site_name: pymwp
site_description: "Implementation of MWP analysis on C code in Python."
docs_dir: docs
site_dir: pages
repo_url: https://github.com/seiller/pymwp
repo_name: seiller/pymwp
edit_uri: blob/master/docs/
use_directory_urls: true


nav:
- Overview: index.md
- Features: features.md
- Examples: examples.md
- Demo: demo.md
- All documented modules:
  - Analysis: analysis.md
  - File I/O: file_io.md
  - Matrix: matrix.md
  - Monomial: monomial.md
  - Polynomial: polynomial.md
  - Relation: relation.md
  - Relation List: relation_list.md
  - Semiring: semiring.md
- Source Code: https://github.com/seiller/pymwp
- License: https://github.com/seiller/pymwp/blob/master/LICENCE.md

theme:
  name: material
  favicon: ""
  features:
    - navigation.expand
  palette:
    scheme: light
    primary: blue grey
    accent: indigo
  font:
    text: Inter
    code: Source Code Pro

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      linenums: false
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.magiclink
  - admonition

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
          - import sys
          - sys.path.append("pymwp")
          selection:
            new_path_syntax: yes
            filters:
              - "^__init__$"
          rendering:
            show_root_heading: false
            show_source: true
            show_category_heading: false
      watch:
        - pymwp

extra_css:
  - assets/styles.css

extra_javascript:
  - //cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/config.js
