name: Automated build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint source
      run: |
        flake8 ./pymwp --count --show-source --statistics

    - name: Run unit tests
      run: |
        pytest --cov=./pymwp tests

    - name: Update pages
      run: |
        pip install mkdocs mkdocs-material mkdocstrings
        mkdocs gh-deploy