name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Lint source
      run: |
        flake8 ./pymwp --count --show-source --statistics

    - name: Run unit tests
      run: |
        pytest --cov=./pymwp tests

    - name: Report coverage
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: false