name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: python -m pip install -r requirements-dev.txt

    - name: Lint source
      run:  make lint-only

    - name: Run unit tests
      run: pytest --cov=./pymwp tests --cov-report=xml

    - uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml

    - name: Docs sanity test
      run: mkdocs build

    - name: Report coverage
      uses: codecov/codecov-action@v3.1.4
      with:
        files: ./coverage.xml
        fail_ci_if_error: false