name: Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Docs setup
      run: |
        python -m pip install -r requirements-dev.txt
        git config user.name 'Bot'
        git config user.email 'the-au-forml-lab@users.noreply.github.com'   
        echo "VERSION=$(python setup.py --version)" >> $GITHUB_ENV
        git fetch origin gh-pages --depth=1

    - name: Update pages
      run: |
        mkdocs build
        mike set-default ${{ env.VERSION }}
        mike deploy --push --update-aliases ${{ env.VERSION }} latest
