name: Profile

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    branches: [ main ]

jobs:
  profile-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: kenchan0130/actions-system-info@master
        id: system-info

      - name: Check outputs
        run: |
          OUTPUTS=(
            "CPU Core: ${{ steps.system-info.outputs.cpu-core }}"
            "CPU Model: ${{ steps.system-info.outputs.cpu-model }}"
            "Hostname: ${{ steps.system-info.outputs.hostname }}"
            "Kernel release: ${{ steps.system-info.outputs.kernel-release }}"
            "Name: ${{ steps.system-info.outputs.name }}"
            "Platform: ${{ steps.system-info.outputs.platform }}"
            "Release: ${{ steps.system-info.outputs.release }}"
            "Total memory bytes: ${{ steps.system-info.outputs.totalmem }}"
          )
          IS_EMPTY_OUTOUT=false
          for OUTPUT in "${OUTPUTS[@]}";do
            echo "${OUTPUT}"
            OUT=$(echo ${OUTPUT} | cut -d ':' -f2- | xargs)
            if [[ -z "${OUT}" ]];then
              IS_EMPTY_OUTOUT=true
            fi
          done
          if "$IS_EMPTY_OUTOUT";then
            exit 1
          fi

      - name: Run profiler
        run: make profile

      - name: Save profiler results
        uses: actions/upload-artifact@v2
        with:
          name: cProfile results
          path: profile/*.txt
          retention-days: 7

      - uses: vimtor/action-zip@v1
        with:
          files: output/profile/*.txt
          dest: profile.zip

      - name: release results
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: "profile-latest"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          draft: false
          files: profile.zip