name: Publish & Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Build Python distribution and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install build setuptools wheel twine

      - name: Run tests
        run: make test

      - uses: vimtor/action-zip@v1.1
        with:
          files: c_files/
          dest: examples.zip

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m build
          python -m twine upload dist/*

      - name: Github release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ github.workspace }}/examples.zip