name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    if: github.actor == 'nkrusch' || github.actor == 'aubertc' ||
        github.actor== 'ThomasRuby'  || github.actor== 'seiller'
    name: Build Python distribution and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel twine

      - name: Run tests
        run: make test

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m build
          python -m twine upload dist/*

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}