name: Python v

on:
  pull_request:
    branches: [ master ]

jobs:
  pyversion:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: pip install --upgrade pipenv

      - name: Run tests
        run: make test
