name: Version test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pyversion:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # test legacy runtimes only; build workflow is set to latest
        python: [ 3.7, 3.8, 3.9 ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Run tests
        run: |
          python3 -m pip install -q -r requirements-dev.txt
          make test-only
